package user

import (
	"google.golang.org/appengine/datastore"
	"quiz"
)

// Statistics for the user, either per quiz (SectionId is then empty), or per section in a quiz.
type Stats struct {
	// The autogenerated ID.
	// We should be able to populate this from datastore.Get() calls automatically,
	// with datastore.Put() calls ignoring it:
	//   https://godoc.org/cloud.google.com/go/datastore#hdr-Key_Field
	// Key *datastore.Key `json:"-" datastore:"__key__"`
	// But that does not seem to actually work:
	//   https://github.com/GoogleCloudPlatform/google-cloud-go/issues/453#issuecomment-328797122
	// So we instead set it manually after each Get() and after each Put().
	Key *datastore.Key `json:"-"`

	UserId *datastore.Key `json:"-" datastore:"userId"`

	QuizId    string `json:"quizId,omitEmpty" datastore:"quizId"`
	SectionId string `json:"sectionId,omitEmpty" datastore:"sectionId"`

	Answered int `json:"answered" datastore:"answered"`
	Correct  int `json:"correct" datastore:"correct"`

	CountQuestionsAnsweredOnce int `json:"countQuestionsAnsweredOnce" datastore:"countQuestionsAnsweredOnce"`
	CountQuestionsCorrectOnce  int `json:"countQuestionsCorrectOnce" datastore:"countQuestionsCorrectOnce"`

	// These are from the quiz, for convenience
	// so they don't need to be in the database.
	// TODO: Make sure they are set for per-section stats.
	CountQuestions int `json:"countQuestions" datastore:"-"`
	QuizTitle    string `json:"quizTitle,omitEmpty" datastore:"-"`
	SectionTitle string `json:"sectionTitle,omitEmpty" datastore:"-"`
}

/** Add the values from userStat to this instance,
* returning a combined UserStats,
* ignoring the question histories,
* without changing this instance.
*/
func (self *Stats) CreateCombinedUserStatsWithoutQuestionHistories(stats *Stats) *Stats {
	if stats == nil {
		return self
	}

	var result Stats
	result.UserId = self.UserId
	result.QuizId = self.QuizId

	result.Answered = self.Answered + stats.Answered
	result.Correct = self.Correct + stats.Correct

	result.CountQuestionsAnsweredOnce = self.CountQuestionsAnsweredOnce + stats.CountQuestionsAnsweredOnce
	result.CountQuestionsCorrectOnce = self.CountQuestionsCorrectOnce + stats.CountQuestionsCorrectOnce

	return &result
}

func (self *Stats) IncrementAnswered() {
	self.Answered += 1
}

func (self *Stats) IncrementCorrect() {
	self.Correct += 1
}

func (self *Stats) UpdateProblemQuestion(question *quiz.Question, answerIsCorrect bool) {
	// TODO
}
