package user

import (
	"cloud.google.com/go/datastore"
)

// Statistics for the user, either per quiz (SectionId is then empty), or per section in a quiz.
type Stats struct {
	// The autogenerated ID.
	// With some versions of appengine's datastore,
	// we should be able to populate this from datastore.Get() calls automatically,
	// with datastore.Put() calls ignoring it:
	//   https://godoc.org/cloud.google.com/go/datastore#hdr-Key_Field
	// Key *datastore.Key `datastore:"__key__"`
	// But that does not work with the appengine datastore we are using:
	//   https://github.com/GoogleCloudPlatform/google-cloud-go/issues/453#issuecomment-328797122
	// So we instead set it manually after each Get() and after each Put().
	Key *datastore.Key `datastore:"-"`

	UserId *datastore.Key `datastore:"userId"`

	QuizId    string `datastore:"quizId"`
	SectionId string `datastore:"sectionId"`

	Answered int `datastore:"answered"`
	Correct  int `datastore:"correct"`

	CountQuestionsAnsweredOnce int `datastore:"countQuestionsAnsweredOnce"`
	CountQuestionsCorrectOnce  int `datastore:"countQuestionsCorrectOnce"`

	// Note: Go's datastore API doesn't let us use a map,
	// though Java's does let us use a Map.
	// (either QuestionHistories map[string]*QuestionHistory or QuestionHistories map[string]QuestionHistory )
	// Also, Go's datastore API (at least the appengine fork of it)
	// doesn't let us use []*QuestionHistory - only []QuestionHistory.
	QuestionHistories []QuestionHistory `datastore:"questionHistories"`
}
