package user

import (
	"cloud.google.com/go/datastore"
	"github.com/murraycu/go-bigoquiz-server/domain/quiz"
)

// Statistics for the user, either per quiz (SectionId is then empty), or per section in a quiz.
type Stats struct {
	// The autogenerated ID.
	// With some versions of appengine's datastore,
	// we should be able to populate this from datastore.Get() calls automatically,
	// with datastore.Put() calls ignoring it:
	//   https://godoc.org/cloud.google.com/go/datastore#hdr-Key_Field
	// Key *datastore.Key `datastore:"__key__"`
	// But that does not work with the appengine datastore we are using:
	//   https://github.com/GoogleCloudPlatform/google-cloud-go/issues/453#issuecomment-328797122
	// So we instead set it manually after each Get() and after each Put().
	Key *datastore.Key `datastore:"-"`

	UserId *datastore.Key `datastore:"userId"`

	QuizId    string `datastore:"quizId"`
	SectionId string `datastore:"sectionId"`

	Answered int `datastore:"answered"`
	Correct  int `datastore:"correct"`

	CountQuestionsAnsweredOnce int `datastore:"countQuestionsAnsweredOnce"`
	CountQuestionsCorrectOnce  int `datastore:"countQuestionsCorrectOnce"`

	// Note: Go's datastore API doesn't let us use a map,
	// though Java's does let us use a Map.
	// (either QuestionHistories map[string]*QuestionHistory or QuestionHistories map[string]QuestionHistory )
	// Also, Go's datastore API (at least the appengine fork of it)
	// doesn't let us use []*QuestionHistory - only []QuestionHistory.
	QuestionHistories []QuestionHistory `datastore:"questionHistories"`
}

func (self *Stats) GetQuestionCountAnsweredWrong(questionId string) int {
	qh, ok := self.getQuestionHistoryForQuestionId(questionId)
	if !ok {
		return 0
	}

	return qh.CountAnsweredWrong
}

func (self *Stats) GetQuestionWasAnswered(questionId string) bool {
	_, found := self.getQuestionHistoryForQuestionId(questionId)
	return found
}

func (self *Stats) IncrementAnswered() {
	self.Answered += 1
}

func (self *Stats) IncrementCorrect() {
	self.Correct += 1
}

func (self *Stats) getQuestionHistoryForQuestionId(questionId string) (*QuestionHistory, bool) {
	if self.QuestionHistories == nil {
		return nil, false
	}

	// TODO: Performance.
	// We would ideally use a map here,
	// but Go's datastore library does not allow that as an entity field type.
	for i := range self.QuestionHistories {
		qh := &self.QuestionHistories[i]
		if qh.QuestionId == questionId {
			return qh, true
		}
	}

	return nil, false
}

func (self *Stats) UpdateProblemQuestion(question *quiz.Question, answerIsCorrect bool) {
	questionId := question.Id
	if len(questionId) == 0 {
		// Log.error("updateProblemQuestion(): questionId is empty.");
		return
	}

	firstTimeAsked := false
	firstTimeCorrect := false

	questionHistory, exists := self.getQuestionHistoryForQuestionId(questionId)

	//Add a new one, if necessary:
	if !exists {
		firstTimeAsked = true
		if answerIsCorrect {
			firstTimeCorrect = true
		}

		questionHistory = new(QuestionHistory)
		questionHistory.QuestionId = question.Id
	} else if answerIsCorrect && !questionHistory.AnsweredCorrectlyOnce {
		firstTimeCorrect = true
	}

	//Increase the wrong-answer count:
	questionHistory.AdjustCount(answerIsCorrect)

	if firstTimeAsked {
		self.CountQuestionsAnsweredOnce++
	}

	if firstTimeCorrect {
		self.CountQuestionsCorrectOnce++
	}

	if !exists {
		self.QuestionHistories = append(self.QuestionHistories, *questionHistory)
	}
	//TODO? cacheIsInvalid = true;
}

func (self *QuestionHistory) AdjustCount(result bool) {
	if result {
		self.AnsweredCorrectlyOnce = true
	}

	if result {
		self.CountAnsweredWrong -= 1
	} else {
		self.CountAnsweredWrong += 1
	}
}
